- name: Import common repository configuration
  ansible.builtin.include_vars: config_common.yaml

- name: Import distro-specific repository configuration
  ansible.builtin.include_vars: config_{{ ansible_distribution }}.yaml

- name: Configure OS settings
  when: system_config['categories']['os']
  block:
  - name: Configure sysctl params
    become: true
    ansible.posix.sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      state: present
      reload: true
      sysctl_set: true
      sysctl_file: /etc/sysctl.d/99-custom.conf
    with_items:
    - {name: vm.swappiness, value: 10}
    - {name: user.max_user_namespaces, value: 28633}
    - {name: kernel.nmi_watchdog, value: 0}

  - name: Remove subuid/subgid configuration for current user if present
    become: true
    when: system_config['categories']['os']
    ansible.builtin.lineinfile:
      regex: .*{{ ansible_user_id }}.*
      state: absent
      path: '{{ item }}'
    with_items:
    - /etc/subuid
    - /etc/subgid

  - name: Add new subuid/subgid configuration for current user
    become: true
    ansible.builtin.shell: |
      usermod --add-subuids 200000-265535 {{ ansible_user_id }}
      usermod --add-subgids 200000-265535 {{ ansible_user_id }}
    register: subugid_cfg
    changed_when: subugid_cfg.rc != 0

- name: Configure software repositories
  when: system_config['categories']['software_repositories']
  block:
  - name: Enable common external repositories
    become: true
    ansible.builtin.shell: |
      if [ "{{ common_repositories['shell'] }}" = "True" ]; then
        {{ common_repositories['list'] | join(' ') }}
      else
        {{ common_repositories['install_command'] }} {{ common_repositories['list'] | join(' ') }}
      fi

  - name: Enabel distro-specific repositories
    become: true
    ansible.builtin.shell: |
      if [ "{{ distro_specific_repositories['shell'] }}" = "True" ]; then
        {{ distro_specific_repositories['list'] | join(' ') }}
      else
        {{ distro_specific_repositories['install_command'] }} {{ distro_specific_repositories['list'] | join(' ') }}
      fi
