---
- name: Configure sysctl params
  become: true
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: true
    sysctl_set: true
    sysctl_file: "/etc/sysctl.d/99-custom.conf"
  with_items:
    - { name: "vm.swappiness", value: 10 }
    - { name: "kernel.unprivileged_userns_clone", value: 1 }
    - { name: "user.max_user_namespaces", value: 28633 }


- name: Remove subuid/subgid configuration for current user if present
  become: true
  ansible.builtin.lineinfile:
    regex: ".*{{ ansible_user_id }}.*"
    state: absent
    path: "{{ item }}"
  with_items:
    - /etc/subuid
    - /etc/subgid

- name: Add new subuid/subgid configuration for current user
  become: true
  ansible.builtin.shell: |
    usermod --add-subuids 200000-265535 {{ ansible_user_id }}
    usermod --add-subgids 200000-265535 {{ ansible_user_id }}
  register: subugid_cfg
  changed_when: subugid_cfg.rc != 0
