system_config:
  enabled: true
  categories:
    os: true
    system_services: true
    software_repositories: true

package_install:
  enabled: true
  categories:
    system_utils: true
    dev_tools: true
    container_runtimes: true
    cluster_tools: true
    multimedia_plugins: true
    fonts: true
    gui_apps: true
    themes: true
    desktop_environments: true
    compilers_and_sdks: true

userenv_config:
  enabled: true
  categories:
    applications: true
    user_services: true
    desktop: true

development_setup:
  enabled: true
  categories:
    tools: true
    ides: true
    editors: true
    sdks_and_runtimes: true
    docker_images: true
    credentials_config: true

backup_list:
  # - src: "{{ ansible_user_dir }}/backup.tar.gz"
  #   dest: "{{ ansible_user_dir }}"
