system_config:
  enabled: false
  categories:
    os: false
    system_services: false

repository_configuration:
  enabled: false

package_install:
  enabled: false
  categories:
    system_utils: false
    dev_tools: false
    container_runtimes: false
    multimedia_plugins: false
    fonts: false
    gui_apps: false
    themes: false
    desktop_environments: false
    compilers_and_sdks: false

userenv_config:
  enabled: false
  categories:
    desktop: false
    dotfiles: false

development_setup:
  enabled: false
  categories:
    tools: false
    ides: false
    editors: false
    sdks_and_runtimes: false
    docker_images: false
    credentials_config: false
    cluster_tools: false

network_configuration:
  enabled: false
  ap_config:
    use_hostapd: false
    ssid: 'Hotspot-pi'
    passphrase: '12345678'
    wireless_config:
      interface_name: 'wlan0'
      ip_address: '10.1.1.1/24'
      country_code: 'US'
      channel: 36
      width: 40 # 20/40/80 mhz
      band: 'a' # a/b/g/n
      capabilities:
        ht: '[HT40+][SHORT-GI-20][SHORT-GI-40][DSSS_CK-40][MAX-AMSDU-3839]'   # Configure this based on the device
        vht: '[SHORT-GI-80][MAX-MPDU-3895][SU-BEAMFORMEE][+HTC-VHT][RX-LDPC]' # Configure this based on the device
        he:                                                                   # Configure this based on the device
