---
install_candidates:
  - { name: system_utils, install: false }
  - { name: dev_tools, install: false }
  - { name: container_tools, install: false }
  - { name: multimedia, install: false }
  - { name: fonts, install: false }
  - { name: compilers_and_runtimes, install: false }

setup_config:
  vscode_setup: false

backup_list:
  # - src: "{{ ansible_user_dir }}/backup.tar.gz"
  #   dest: "{{ ansible_user_dir }}"
