---
- name: Start post install configuration
  hosts: localhost
  connection: local

  tasks:
    - name: Dump hostvars
      tags:
        - never
        - debug
      ansible.builtin.copy:
        content: var="{{ hostvars[inventory_hostname] | to_nice_json }}"
        dest: /tmp/dump.json
        mode: "0644"

    - name: Package install
      tags: package_install
      ansible.builtin.include_role:
        name: package_install
        apply:
          tags: package_install

    - name: User environment configuration
      tags: userenv_config
      ansible.builtin.include_role:
        name: user_environment_configuration
        apply:
          tags: userenv_config
