- name: Start post install configuration
  hosts: localhost
  connection: local

  tasks:
  - name: Dump hostvars
    tags:
    - never
    - debug
    ansible.builtin.copy:
      content: "{{ hostvars[inventory_hostname] | to_nice_json }}"
      dest: /tmp/dump.json
      mode: '0644'

  - name: System update
    tags: system_update
    ansible.builtin.include_role:
      name: system_update
      apply:
        tags: system_update

  - name: Repository configuration
    tags: repository_configuration
    ansible.builtin.include_role:
      name: repository_configuration
      apply:
        tags: repository_configuration
    when: repository_configuration['enabled']

  - name: Package install
    tags: package_install
    ansible.builtin.include_role:
      name: package_install
      apply:
        tags: package_install
    when: package_install['enabled']

  - name: System configuration
    tags: system_config
    ansible.builtin.include_role:
      name: system_configuration
      apply:
        tags: system_config
    when: system_config['enabled']

  - name: User environment configuration
    tags: userenv_config
    ansible.builtin.include_role:
      name: user_environment_configuration
      apply:
        tags: userenv_config
    when: userenv_config['enabled']

  - name: Development Setup
    tags: dev_setup
    ansible.builtin.include_role:
      name: development_setup
      apply:
        tags: dev_setup
    when: development_setup['enabled']

  - name: Raspberry-pi configuration
    when: network_configuration['enabled']
    tags: network_configuration
    ansible.builtin.include_role:
      name: network_configuration
      apply:
        tags: network_configuration
