- name: Load user dotfiles
  when: userenv_config['categories']['dotfiles']
  ansible.builtin.copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
  - {src: dotfiles/.profile, dest: '{{ ansible_user_dir }}/'}
  - {src: dotfiles/.bashrc, dest: '{{ ansible_user_dir }}/'}
  - {src: dotfiles/.local/, dest: '{{ ansible_user_dir }}/'}
  - {src: dotfiles/.config/containers/, dest: '{{ ansible_user_dir }}/.config/'}
  - {src: dotfiles/.config/helix/, dest: '{{ ansible_user_dir }}/.config/'}
  - {src: dotfiles/.config/mpv/, dest: '{{ ansible_user_dir }}/.config/'}
  - {src: dotfiles/.config/tmux/, dest: '{{ ansible_user_dir }}/.config/'}

- name: Configure desktop
  when: userenv_config['categories']['desktop']
  block:
  - name: Load dconf settings
    ansible.builtin.shell: |
      cat dconf.conf | dconf load /

  - name: Load sway configuration
    ansible.builtin.copy:
      src: '{{ item.src }}'
      dest: '{{ item.dest }}'
    with_items:
    - {src: dotfiles/.config/sway/, dest: '{{ ansible_user_dir }}/.config/'}
    - {src: dotfiles/.config/waybar/, dest: '{{ ansible_user_dir }}/.config/'}
