---
- name: Configure vim/neovim
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  with_items:
    - { src: init.vim, dest: "{{ ansible_user_dir }}/.config/nvim/init.vim" }
    - { src: .vimrc, dest: "{{ ansible_user_dir }}/.vimrc" }
    - { src: plug.vim, dest: "{{ ansible_user_dir }}/.local/share/nvim/site/autoload" }

- name: Install custom utilities
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0755"
  with_items:
    - { src: dirsize, dest: "{{ ansible_user_dir }}/.local/bin/dirsize" }
    - { src: git_starter, dest: "{{ ansible_user_dir }}/.local/bin/git_starter" }
    - { src: mkfile, dest: "{{ ansible_user_dir }}/.local/bin/mkfile" }
    - { src: renamer, dest: "{{ ansible_user_dir }}/.local/bin/renamer" }

- name: Get backup configuration
  ansible.builtin.include_vars: "backup.yml"

- name: Restore backup
  ansible.builtin.unarchive:
    src: "{{ item.src }}"
    owner: "{{ ansible_effective_user_id }}"
    group: "{{ ansible_effective_group_id }}"
    dest: "{{ item.dest }}"
  with_items:
    "{{ backup_list }}"
  when: backup_list
