---
- name: Configure vim/neovim
  ansible.builtin.command: |
    git clone --recursive https://github.com/nnishant776/init.lua ~/.config/nvim -b dev

- name: Install custom utilities
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0755"
  with_items:
    - { src: dirsize, dest: "{{ ansible_user_dir }}/.local/bin/" }
    - { src: git_starter, dest: "{{ ansible_user_dir }}/.local/bin/" }
    - { src: mkfile, dest: "{{ ansible_user_dir }}/.local/bin/" }
    - { src: renamer, dest: "{{ ansible_user_dir }}/.local/bin/" }

- name: Restore backup
  ansible.builtin.unarchive:
    src: "{{ item.src }}"
    owner: "{{ ansible_effective_user_id }}"
    group: "{{ ansible_effective_group_id }}"
    dest: "{{ item.dest }}"
  with_items:
    "{{ backup_list }}"
  when: backup_list
