---
- name: Configure vim/neovim
  copy: src="{{ item.src }}" dest="{{ item.dest }}"
  with_items:
    - { src: init.vim, dest: "{{ ansible_user_dir }}/.config/nvim/init.vim" }
    - { src: .vimrc, dest: "{{ ansible_user_dir }}/.vimrc" }
    - {
        src: plug.vim,
        dest: "{{ ansible_user_dir }}/.local/share/nvim/site/autoload",
      }

- name: Configure custom utilities
  become: true
  copy: src="{{ item.src }}" dest="{{ item.dest }}" mode=u=rwx,g=rx,o=rx
  with_items:
    - { src: dirsize, dest: /usr/local/bin/dirsize }
    - { src: git_starter, dest: /usr/local/bin/git_starter }
    - { src: mkfile, dest: /usr/local/bin/mkfile }
    - { src: renamer, dest: /usr/local/bin/renamer }
