- name: Load user dotfiles
  when: userenv_config['categories']['dotfiles']
  ansible.builtin.copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    force: true
    directory_mode: '0755'
    mode: 'preserve'
  with_items:
  - {src: dotfiles/, dest: '{{ ansible_user_dir }}/'}
  - {src: dconf.conf, dest: '{{ ansible_user_dir }}/.config/dconf/'}

- name: Configure desktop
  when: userenv_config['categories']['desktop']
  block:
  - name: Load dconf settings
    ansible.builtin.shell: |
      cat {{ ansible_user_dir }}/.config/dconf/dconf.conf | dconf load /

  - name: Load sway configuration
    ansible.builtin.copy:
      src: '{{ item.src }}'
      dest: '{{ item.dest }}'
    with_items:
    - {src: dotfiles/.config/sway/, dest: '{{ ansible_user_dir }}/.config/'}
    - {src: dotfiles/.config/waybar/, dest: '{{ ansible_user_dir }}/.config/'}
