- name: Import common repository configuration
  ansible.builtin.include_vars: config_common.yaml

- name: Import distro-specific repository configuration
  ansible.builtin.include_vars: config_{{ ansible_distribution }}.yaml

- name: Configure software repositories
  become: true
  block:
  - name: Enable common external repositories
    ansible.builtin.shell: |
      if [ "{{ common_repositories['shell'] }}" = "True" ]; then
        {{ common_repositories['list'] | join(' ') }}
      else
        {{ common_repositories['install_command'] }} {{ common_repositories['list'] | join(' ') }}
      fi

  - name: Enabel distro-specific repositories
    ansible.builtin.shell: |
      if [ "{{ distro_specific_repositories['shell'] }}" = "True" ]; then
        {{ distro_specific_repositories['list'] | join(' ') }}
      else
        {{ distro_specific_repositories['install_command'] }} {{ distro_specific_repositories['list'] | join(' ') }}
      fi
