- name: Import common package list
  ansible.builtin.include_vars: pkglist_common.yaml

- name: Import flatpak package list
  ansible.builtin.include_vars: pkglist_flatpak.yaml

- name: Import distro-specific package list
  ansible.builtin.include_vars:
    file: "{{ item }}"
  with_first_found:
    - files:
        - 'vars/pkglist_{{ ansible_distribution }}.yaml'
        - 'vars/pkglist_{{ ansible_os_family }}.yaml'

- name: Install packages
  ansible.builtin.include_tasks:
    file: "{{ item }}"
  with_first_found:
    - files:
        - 'tasks_{{ ansible_distribution }}.yaml'
        - 'tasks_{{ ansible_os_family }}.yaml'
        - 'default.yaml'
