---
############################# Import package list #############################

- name: Import common package list
  ansible.builtin.include_vars: "pkglist_common.yml"

- name: Import distro-specific package list
  ansible.builtin.include_vars: "pkglist_{{ ansible_distribution }}.yml"

- name: Import flatpak package list
  ansible.builtin.include_vars: "pkglist_flatpak.yml"

######################## Install the selected packages ########################

- name: Enable additional repositories
  become: true
  ansible.builtin.shell: |
    dnf -y install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
    dnf -y install https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
  when: ansible_distribution == "Fedora"

- name: Install common packages
  become: true
  ansible.builtin.package:
    name: "{{ common_package_list }}"
    state: present

- name: Install distro-specific packages
  become: true
  ansible.builtin.package:
    name: "{{ distro_package_list[item.name] }}"
    state: present
  when: item.install
  loop: "{{ install_candidates }}"

- name: Install flatpak packages
  community.general.flatpak:
    name: "{{ flatpak_package_list }}"
    state: present
    remote: flathub
    method: system
