- name: Update flatpak packages
  become: true
  ansible.builtin.command: /usr/bin/flatpak update -y
  ignore_errors: true

- name: Update system packages
  become: true
  ansible.builtin.package:
    name: '*'
    state: latest
