---
distro_package_list:
  # System-Utility packages
  system_utils:
    - fuse-sshfs
    - openssh-server
    - python3-pip
    - p7zip
    - p7zip-plugins
    - nethogs
    - feh
    - lm_sensors
    - ibus-table-code
    - iucode-tool
    - microcode_ctl
    - intltool
    - d-feet
    - la-capitaine-cursor-theme
    - gnome-extensions-app
    - file-roller

  # Developer Tools
  dev_tools:
    - gh
    - git
    - gitk

  # Programming Language Compilers and Runtimes
  compilers_and_runtimes:
    - gcc
    - clang
    - gdb
    - lldb
    - lld
    - llvm
    - "@C Development Tools and Libraries"
    - golang
    - golang-bin
    - java-latest-openjdk
    - nodejs

  # Container management
  container_tools:
    - "@Container Management"
    - docker

  # Multimedia packages
  multimedia:
    - chromium-vaapi
    - ffmpeg-free
    - dav1d
    - mozilla-openh264
    - gstreamer1-plugin-libav
    - gstreamer1-plugin-openh264
    - gstreamer1-plugins-base
    - gstreamer1-plugins-good
    - gstreamer1-plugins-good-extras
    - gstreamer1-plugins-bad-free
    - gstreamer1-plugins-bad-free-extras
    - gstreamer1-plugins-bad-free-zbar
    - gstreamer1-plugins-bad-freeworld
    - gstreamer1-plugins-ugly
    - gstreamer1-plugins-ugly-free
    - gstreamer1-vaapi
    - gst-entrans
    - faad2-libs
    - libde265
    - fluidsynth-libs
    - libmatroska
    - libspatialaudio
    - libmpcdec
    - live555
    - libebml
    - freeglut
    - libplacebo
    - mesa-libGLU
    - gnome-mpv
    - kodi

  # Font packages
  fonts:
    - mozilla-fira-*
    - fira-code-fonts
    - adobe-source-code-pro-fonts
    - adobe-source-sans-pro-fonts
    - dejavu-fonts-all
    - google-droid-sans-fonts
    - google-noto-sans-fonts
    - google-noto-serif-fonts
    - google-roboto-fonts
    - google-roboto-condensed-fonts
    - google-roboto-mono-fonts
    - liberation-fonts
    - liberation-sans-fonts
    - liberation-mono-fonts
    - liberation-serif-fonts
    - dejavu-sans-fonts
    - dejavu-sans-mono-fonts
