distro_package_list:
  # System-Utility packages
  system_utils:
    - sshfs
    - openssh
    - python-pip
    - lm_sensors
    - ibus-table
    - iucode-tool
    - intel-ucode
    - intltool
    - tar
    - gzip
    - unzip
    - unrar
    - zstd
    - efitools
    - wev
    - nfs-utils
    - gvfs-nfs
    - rpcbind
    - nfsidmap

  # GUI Tools
  gui_apps:
    - gnome-shell-extensions
    - gnome-tweaks
    - file-roller
    - blueman
    - gnome-shell-extension-appindicator
    - dconf
    - dconf-editor
    - celluloid

  # Themes
  themes:
    - capitaine-cursors
    # - adw-gtk3-theme

  # Desktop environments
  desktop_environments:
    - sway
    - swaybg
    - swayidle
    - swayimg
    - swaylock
    - sway-contrib
    - waybar
    - wf-recorder
    - wofi
    - slurp
    - grim
    - rofi-wayland

  # Development Tools
  dev_tools:
    - github-cli

  # Programming Language Compilers and Runtimes
  compilers_and_sdks:
    - gcc
    - clang
    - gdb
    - lldb
    - lld
    - llvm
    - base-devel
    - go
    - jre-openjdk
    - nodejs

  # Container management
  container_runtimes:
    - docker
    - podman
    - slirp4netns

  # Multimedia packages
  multimedia_plugins:
    - ffmpeg
    - gst-libav
    - gst-plugin-va
    - gst-plugins-base
    - gst-plugins-good
    - gst-plugins-bad
    - gst-plugins-ugly
    - gstreamer
    - gstreamer-vaapi
    - pipewire
    - pipewire-audio
    - pipewire-jack
    - pipewire-pulse
    - pipewire-v4l2
    - wireplumber
    - libfreeaptx
    - libldac
    - faad2
    - fdkaac
    - alsa-firmware
    - alsa-plugins
    - a52dec
    - x264
    - x265
    - libmatroska
    - vulkan-intel
    - vulkan-radeon

  # Font packages
  fonts:
    - woff-fira-code
    - woff2-fira-code
