---
distro_package_list:
  # System-Utility packages
  system_utils:
    - sshfs
    - openssh-server
    - python3-pip
    - p7zip-full
    - lm-sensors
    - ibus-table-code
    - iucode-tool
    - intltool

  # GUI Tools
  gui_apps:
    - gnome-shell-extensions
    - gnome-tweaks
    - file-roller
    - blueman
    - d-feet
    - gnome-shell-extension-appindicator
    - dconf-editor
    - celluloid

  # Themes
  themes:
    - breeze-cursor-theme
    # - adw-gtk3-theme

  # Desktop environments
  desktop_environments:
    - vanilla-gnome-desktop

  # Developer Tools
  dev_tools:
    - gh
    - git
    - gitk

  # Programming Language Compilers and Runtimes
  compilers_and_runtimes:
    - gcc
    - clang
    - gdb
    - lldb
    - lld
    - llvm
    - build-essential
    - golang
    - default-jre

  # Container Management
  container_tools:
    - docker.io
    - podman

  # Multimedia packages
  multimedia_plugins:
    - ffmpeg
    - dav1d
    - gstreamer1.0-libav
    - gstreamer1.0-plugins-base
    - gstreamer1.0-plugins-good
    - gstreamer1.0-plugins-bad
    - gstreamer1.0-plugins-ugly
    - gstreamer1.0-vaapi
    - x264
    - x265

  # Font packages
  fonts:
    - fonts-firacode
    - fonts-dejavu
    - fonts-noto
    - fonts-liberation
    - fonts-liberation2
