---
distro_package_list:
  # System-Utility packages
  system_utils:
    - fuse-sshfs
    - openssh-server
    - python3-pip
    - p7zip-plugins
    - lm_sensors
    - ibus-table-code
    - iucode-tool
    - microcode_ctl
    - intltool
    - efitools
    - wev
    - apmd
    - nfs-utils
    - nfsv4-client-utils
    - sssd-nfs-idmap
    - gvfs-nfs
    - rpcbind

  # GUI Tools
  gui_apps:
    - gnome-extensions-app
    - gnome-tweaks
    - file-roller
    - blueman
    - d-feet
    - gnome-shell-extension-appindicator
    - dconf-editor
    - celluloid

  # Themes
  themes:
    - breeze-cursor-theme
    - adw-gtk3-theme

  # Desktop environments
  desktop_environments:
    - "@Sway Window Manager"

  # Developer Tools
  dev_tools:
    - gh
    - git
    - gitk

  # Programming Language Compilers and Runtimes
  compilers_and_runtimes:
    - gcc
    - clang
    - gdb
    - lldb
    - lld
    - llvm
    - "@C Development Tools and Libraries"
    - golang
    - golang-bin
    - java-latest-openjdk
    - nodejs

  # Container management
  container_tools:
    - "@Container Management"
    - docker

  # Multimedia packages
  multimedia_plugins:
    - ffmpeg
    - dav1d
    - mpg123
    - mozilla-openh264
    - gstreamer1-plugin-libav
    - gstreamer1-plugin-openh264
    - gstreamer1-plugins-base
    - gstreamer1-plugins-good
    - gstreamer1-plugins-good-extras
    - gstreamer1-plugins-bad-free
    - gstreamer1-plugins-bad-free-extras
    - gstreamer1-plugins-bad-free-zbar
    - gstreamer1-plugins-bad-freeworld
    - gstreamer1-plugins-ugly
    - gstreamer1-plugins-ugly-free
    - gstreamer1-vaapi
    - faad2-libs
    - libde265
    - fluidsynth-libs
    - libmatroska
    - libspatialaudio
    - libmpcdec
    - live555
    - libebml
    - freeglut
    - libplacebo
    - mesa-libGLU
    - pipewire-codec-aptx
    - libldac
    - fdk-aac
    - fdk-aac-free
    - liba52
    - faac
    - vlc
    - x264
    - x265
    - pipewire-gstreamer
    - pipewire-alsa
    - pipewire-libs
    - pipewire-plugin-jack
    - pipewire-plugin-libcamera
    - pipewire-plugin-vulkan
    - pipewire-v4l2
    - pipewire-utils
    - alsa-firmware
    - alsa-plugins-jack
    - aalib-libs
    - SDL_image
    - alsa-plugins-a52
    - libdav1d

  # Font packages
  fonts:
    - mozilla-fira-*
    - fira-code-fonts
    - adobe-source-code-pro-fonts
    - adobe-source-sans-pro-fonts
    - dejavu-fonts-all
    - google-droid-sans-fonts
    - google-noto-sans-fonts
    - google-noto-serif-fonts
    - google-roboto-fonts
    - google-roboto-condensed-fonts
    - google-roboto-mono-fonts
    - liberation-fonts
    - liberation-sans-fonts
    - liberation-mono-fonts
    - liberation-serif-fonts
    - dejavu-sans-fonts
    - dejavu-sans-mono-fonts
