#!/usr/bin/bash
if [ $(id -u) -ne 0 ];then
    theme_dir=~/.local/share/themes-store
else
    theme_dir=/usr/share/theme-store
fi
cd $theme_dir

if [ ! -d 'shell/WhiteSur-gtk-theme' ];then
    mkdir -p shell
    cd shell
    git clone https://github.com/vinceliuice/WhiteSur-gtk-theme
    cd ..
fi
cd shell/WhiteSur-gtk-theme
git pull
./install.sh -i simple -t blue -N mojave
if [ $(id -u) -eq 0 ];then
    ./tweaks.sh -f -g -D
fi
cd ../../

if [ ! -d 'icons/WhiteSur-icon-theme' ];then
    mkdir -p icons
    cd icons
    git clone https://github.com/vinceliuice/WhiteSur-icon-theme
    cd ..
fi
cd icons/WhiteSur-icon-theme
git pull
./install.sh
cd ../../
